---
- name: Deploy PostgreSQL network config
  template:
    src: "10-network.conf.j2"
    dest: "/etc/postgresql/{{ postgresql_version }}/main/conf.d/10-network.conf"
    owner: postgres
    group: postgres
    mode: "0644"

- name: Deploy pg_hba.conf
  template:
    src: "pg_hba.conf.j2"
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: "0640"

- name: Deploy PostgreSQL main config (password_encryption, etc.)
  template:
    src: "20-main.conf.j2"
    dest: "/etc/postgresql/{{ postgresql_version }}/main/conf.d/20-main.conf"
    owner: postgres
    group: postgres
    mode: "0644"
