---
# ============================
# Keyrings directory
# ============================
- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - postgresql
    - postgresql_install
    - install

# ============================
# PostgreSQL GPG key
# ============================
- name: Download PostgreSQL GPG key
  get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /etc/apt/keyrings/postgresql.asc
    mode: '0644'
  tags:
    - postgresql
    - postgresql_install
    - install

# ============================
# PostgreSQL APT repository
# ============================
- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/postgresql.asc] http://apt.postgresql.org/pub/repos/apt {{ ansible_facts['distribution_release'] }}-pgdg main"
    state: present
  tags:
    - postgresql
    - postgresql_install
    - install

# ============================
# Install PostgreSQL (version from all.yml)
# ============================
- name: Install PostgreSQL {{ postgresql_version }}
  apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - postgresql-contrib
    state: present
    update_cache: yes
  tags:
    - postgresql
    - postgresql_install
    - install
