- name: Enable and restart PostgreSQL
  systemd:
    name: postgresql
    enabled: yes
    state: restarted
  tags:
    - postgresql
    - postgresql_service

- name: Set postgres user password
  become: yes
  shell: |
    sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ postgresql_password }}';"
  tags:
    - postgresql
    - postgresql_password
    - postgresql_service

- name: Verify PostgreSQL is active
  systemd:
    name: postgresql
  register: postgresql_status
  failed_when: postgresql_status.status.ActiveState != "active"
  changed_when: false
  tags:
    - postgresql
    - postgresql_verify
    - verify
    - postgresql_service
