---
- name: Disable default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure empty apps.conf exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/nginx/snippets/apps.conf
    mode: "0644"

- name: Deploy main Nginx config for root site
  ansible.builtin.template:
    src: main.conf.j2
    dest: /etc/nginx/sites-available/main.conf
    mode: "0644"

- name: Enable main site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/main.conf
    dest: /etc/nginx/sites-enabled/main.conf
    state: link

- name: Deploy root site files
  ansible.builtin.copy:
    src: root/
    dest: /var/www/html/
    mode: "0644"
