---
- name: Install Nginx
  import_tasks: install.yml
  tags:
    - nginx
    - nginx_install
    - install

- name: Configure Nginx sites
  import_tasks: config.yml
  tags:
    - nginx
    - nginx_config
    - install

- name: Manage Nginx service
  import_tasks: service.yml
  tags:
    - nginx
    - nginx_service
    - install
