---
- include_tasks: fastapi_install.yml
  tags:
    - webapp
    - fastapi
    - fastapi_install

- include_tasks: fastapi_config.yml
  tags:
    - webapp
    - fastapi
    - fastapi_config

- include_tasks: fastapi_service.yml
  tags:
    - webapp
    - fastapi
    - fastapi_service
