- hosts: local
  become: yes
  roles:
    - common # OS 基本設定
    - php # PHP-FPM + php.ini
    - nginx # nginx install
    - node # Node.js / nvm
    - composer # composer install
    - python # python + uv
    - postgresql # PostgreSQL install + config + backup
    - garnet # Garnet
    - nginx-main # 9000番の振り分け（reverse proxy）
    - express # Express
    - fastapi # FastAPI
