---
- name: Set permissions for app
  ansible.builtin.include_tasks: permissions.yml
  loop: "{{ nginx_apps }}"
  loop_control:
    loop_var: app
  tags:
    - nginx
    - install

- name: Generate apps.conf from template
  ansible.builtin.template:
    src: apps.conf.j2
    dest: /etc/nginx/snippets/apps.conf
    mode: "0644"
  notify: Reload nginx
  tags:
    - nginx
    - install