# ===========================
# 1. Install webawesome
# ===========================
- name: Install tasks
  ansible.builtin.import_tasks: webawesome.yml
  tags: [install, webawesome]
# ===========================
# 2. Install drawio/viewer
# ===========================
- name: Install tasks
  ansible.builtin.import_tasks: drawio.yml
  tags: [install, drawio]
# ===========================
# 3. Install htmx
# ===========================
- name: Install tasks
  ansible.builtin.import_tasks: htmx.yml
  tags: [install, htmx]
