# 初回
# ansible-playbook site.yml --tags nginx_main
# 1.main reverse proxy の config だけ更新
# ansible-playbook site.yml --tags nginx_main_config
# ansible-playbook site.yml --tags nginx_main_reload
# 2.reload
# ansible-playbook site.yml --tags nginx_main_reload
---
- name: Deploy nginx main reverse proxy (port {{ nginx_entry_port }})
  template:
    src: nginx-main.conf.j2
    dest: /etc/nginx/sites-available/main.conf
  tags:
    - nginx_main
    - nginx_main_config

- name: Enable main nginx site
  file:
    src: /etc/nginx/sites-available/main.conf
    dest: /etc/nginx/sites-enabled/main.conf
    state: link
    force: yes
  tags:
    - nginx_main
    - nginx_main_config

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
  tags:
    - nginx_main
    - nginx_main_reload
