- hosts: local
  become: yes
  roles:
    - common # OS 基本設定
    - ollama
    - weaviate
    - siglip2
    - node # Node.js / nvm
    - share
    - php # PHP-FPM + php.ini
    - nginx # nginx install
    - composer # composer install
    - python # python + uv
    - uv # ユーザ用uv
    - postgresql # PostgreSQL install + config + backup
    - postgresql_pg_bigm # pg_bigm
    - garnet # Garnet
    - supervisor
    - paddleocr-build
    - embedding-build
    - emb # build embed-binary cli
    - paddleocr-cli
