---
- include_tasks: install.yml
  tags:
    - postgresql
    - postgresql_install
    - install
- include_tasks: config.yml
  tags:
    - postgresql
    - postgresql_config

- include_tasks: service.yml
  tags:
    - postgresql
    - postgresql_start
    - start

- include_tasks: init.yml
  tags:
    - postgresql
    - postgresql_init
