- name: Install Composer
  shell: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    php -r "unlink('composer-setup.php');"
  args:
    creates: /usr/local/bin/composer
  tags:
    - composer
    - composer_install
    - install
- name: Upgrade Composer to latest version
  shell: composer self-update
  tags:
    - composer
    - composer_upgrade
    - upgrade
