nginx_apps:
  - path: /app1
    type: php
    root: /home/asao/projects/app1/public

  # - path: /app2/
  #   type: php
  #   root: /home/{{ansible_user}}/projects/app2/public

  # - path: /app3/
  #   type: static
  #   root: /home/{{ansible_user}}/projects/app3/dist

  # - path: /express/
  #   type: proxy
  #   target: http://localhost:3000/

  # - path: /fastapi/
  #   type: proxy
  #   target: http://localhost:8000/
