---
- name: Install nvm
  shell: |
    if [ ! -d "/home/{{ ansible_user }}/.nvm" ]; then
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    fi
  become: false
  tags:
    - node
    - node_install
    - install

- name: Load nvm and install Node.js LTS
  shell: |
    export NVM_DIR="/home/{{ ansible_user }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install --lts
  args:
    executable: /bin/bash
  become: false
  tags:
    - node
    - node_install
    - install

- name: Add nvm init to .bashrc
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: 'export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    insertafter: EOF
  become: false
  tags:
    - node
    - node_install
    - install
