# Express のコードだけ更新（git pull + npm install）
# ansible-playbook site.yml --tags express_install
# systemd / nginx の設定だけ更新
# ansible-playbook site.yml --tags express_config
# ansible-playbook site.yml --tags express_service
# 再起動
# ansible-playbook site.yml --tags express_service
# 全体
# ansible-playbook site.yml --tags express

---
- include_tasks: express_install.yml
  tags:
    - webapp
    - express
    - express_install

- include_tasks: express_config.yml
  tags:
    - webapp
    - express
    - express_config

- include_tasks: express_service.yml
  tags:
    - webapp
    - express
    - express_service
