- name: Update apt cache
  apt:
    update_cache: yes
  tags:
    - common

- name: Install base packages
  apt:
    name:
      - git
      - unzip
      - curl
      - software-properties-common
    state: present
  tags:
    - common
    - install
