---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - php
    - php_install
- name: Install PHP-FPM and extensions
  ansible.builtin.apt:
    name:
      - php-fpm
      - php-cli
      - php-mbstring
      - php-xml
      - php-curl
      - php-zip
      - php-intl
      - php-opcache
      - php-redis
    state: present
    update_cache: yes
  tags:
    - php
    - php_install
    - install

- name: Deploy optimized php.ini
  ansible.builtin.template:
    src: php.ini.j2
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
  notify: restart php-fpm
  tags:
    - php
    - php_install
    - php_config
    - install

- name: Check if Redis extension is loaded
  ansible.builtin.command: php -m
  register: php_modules
  tags:
    - php
    - php_check
    - php_install
    - php_config
    - install

- name: Assert Redis is loaded
  ansible.builtin.assert:
    that: "'redis' in php_modules.stdout"
  tags:
    - php
    - php_check
    - php_install
    - php_config
    - install
