---
- name: Deploy Express systemd service
  template:
    src: express.service.j2
    dest: "/etc/systemd/system/{{ item.name }}.service"
  tags:
    - express_config

- name: Deploy nginx backend reverse proxy for Express
  template:
    src: express-nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.name }}.conf"
  tags:
    - express_config

- name: Enable nginx site for Express
  file:
    src: "/etc/nginx/sites-available/{{ item.name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.name }}.conf"
    state: link
    force: yes
  tags:
    - express_config
